const anObject = new Object();
console.log('value of anObject:', anObject);
console.log('typeof anObject:', typeof anObject);
const anArray = new Array();
console.log('value of anArray:', anArray);
console.log('typeof anArray:', typeof anArray);
const anFunction = new Function();
console.log('value of anFunction:', anFunction);
console.log('typeof anFunction:', typeof anFunction);
const anString = new String();
console.log('value of anString:', anString);
console.log('typeof anString:', typeof anString);
const anNumber = new Number();
console.log('value of anNumber:', anNumber);
console.log('typeof anNumber:', typeof anNumber);
const anBoolean = new Boolean();
console.log('value of anBoolean:', anBoolean);
console.log('typeof anBoolean:', typeof anBoolean);
