const width = 2;
const height = 3;
const area = width * height;
console.log(area);
console.log(typeof area);
const bill = 5;
const payment = 10;
const change = payment - bill;
console.log(change);
console.log(typeof change);
const quizzes = 5;
const midterm = 10;
const final = 15;
const grade = (quizzes + midterm + final) / 3;
console.log(grade);
console.log(typeof grade);
const firstName = 'Kyle';
const lastName = ' Kriske';
const fullName = firstName + lastName;
console.log(fullName);
console.log(typeof fullName);
const pH = 3;
const isAcidic = pH < 7;
console.log(isAcidic);
console.log(typeof isAcidic);
const headCount = 500;
// eslint-disable-next-line no-unused-vars
const isSparta = headCount === 300;
console.log(isSparta);
console.log(typeof isSparta);
let motto = fullName;
motto += ' is the GOAT';
console.log(motto);
console.log(typeof motto);
